---
- name: Install Apache2 Package
  apt:
    name: apache2
    state: latest
  notify: Restart Apache2

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: latest
  notify: Restart Fail2Ban

- name: Update Fail2Ban configurations from local configurations
  copy:
    src: /etc/fail2ban/jail.local
    dest: /etc/fail2ban/
  notify: Restart Fail2Ban
